services:
  db:
    image: postgres
    restart: always
    environment:
     POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: blogs-db

volumes:
  pgdata:
